name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage  # Install coverage package

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover

    - name: Generate coverage report
      run: |
        coverage report
        coverage xml  # Generates an XML report for integration with other tools